version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bibliotech-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bibliotech
      POSTGRES_PASSWORD: bibliotech
      POSTGRES_DB: bibliotech
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bibliotech"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    container_name: bibliotech-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://bibliotech:bibliotech@postgres:5432/bibliotech
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRES_IN=1d
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./back_end:/app
      - /app/node_modules

volumes:
  postgres_data: